testing/gameplay: Test when not enough users.
Origionally planed to use HTTPStatus.TOO_EARLY but apparently werkzeug
does not support it out of the box and we get:

	LookupError: no exception for <HTTPStatus.TOO_EARLY: 425> in test_game_play.py